In [1]:
import numpy as np
import pickle

In [5]:
scene_path = "benchmark_data/N10_M4_ends2_seed3"

with open(scene_path, 'rb') as file:
    data = pickle.load(file)
START_locs = data["START_locs"].cpu().detach().numpy()
F_base = data["F_base"].cpu().detach().numpy()
END_locs = data["END_locs"].cpu().detach().numpy()
num_agents = START_locs.shape[0]
num_nodes = F_base.shape[-2]
dim_ = F_base.shape[-1]
T = num_nodes + 1;

In [ ]:
from GurobiSolver import SolveMIP

gap = 0.0
best_y, best_eta, cost, elapsed_time = SolveMIP(
    START_locs, END_locs, num_agents, num_nodes, T, dim_, F_base, gap=gap
)

Set parameter Username
Academic license - for non-commercial use only - expires 2026-07-28
Read LP format model from file C:\Users\salar\AppData\Local\Temp\tmp4l_ent2q.pyomo.lp
Reading time = 0.00 seconds
x1: 136 rows, 408 columns, 548 nonzeros
Set parameter NonConvex to value 2
Set parameter MIPGap to value 0
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (win64 - Windows 11+.0 (26100.2))

CPU model: 13th Gen Intel(R) Core(TM) i7-13620H, instruction set [SSE2|AVX|AVX2]
Thread count: 10 physical cores, 16 logical processors, using up to 16 threads

Optimize a model with 136 rows, 408 columns and 548 nonzeros
Model fingerprint: 0xda968c46
Model has 150 quadratic constraints
Variable types: 158 continuous, 250 integer (250 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [2e-01, 1e+00]
  Objective range  [1e-01, 1e-01]
  Bounds range     [5e-02, 1e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [8e-02, 1e+0

In [4]:
print("Best y:", best_y)
print("Best eta:", best_eta)
print("Cost:", cost)
print("Elapsed time:", elapsed_time)

Best y: [[0.5027801  0.33358121]
 [0.59879445 0.30835901]
 [0.71553494 0.24699215]
 [0.83227579 0.18562672]]
Best eta: [[[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[1. 0.