In [1]:
from utils import route_cost, generate_unit_circle_cities
from TSPNet_TF import TSPNet
from data_loader_script import create_data_loader
from train import train
import torch
from datetime import datetime
import torch.multiprocessing as mp
from torch.utils.tensorboard import SummaryWriter
import argparse

mp.set_start_method('spawn', force=True)

In [2]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
device

device(type='cuda')

In [3]:
def preload_data(data_loader, device):
    preloaded_batches = []
    for data_batch in data_loader:
        preloaded_batches.append(data_batch.to(device, non_blocking=True))
    return preloaded_batches

lr = 0.001
batch_size = 64
num_episodes = 6000
num_samples = batch_size * num_episodes
num_cities = 50
input_dim = 2
num_workers = 8  #

data_loader = create_data_loader(batch_size, num_samples, num_cities, input_dim, num_workers=num_workers)
preloaded_batches = preload_data(data_loader, device)

run_name = 'TSP/' + str(batch_size) + '_' + str(num_cities) + '_' + str(num_samples) + '_' + '/ANN/'+datetime.now().strftime(("%Y_%m_%d %H_%M_%S"))+ str(True) + str(0.1)
writer = SummaryWriter(log_dir=run_name)



In [ ]:
from torchinfo import summary


hidden_dim = 64
num_layers = 3
num_heads = 8

model = TSPNet(input_dim,hidden_dim,device,num_heads=num_heads,num_enc_layers=num_layers,num_dec_layers=num_layers,use_PE=False)

summary(model)

trained = train(model, preloaded_batches, writer, lr, use_base = True, alpha=0.1,check_params=False)

In [3]:
import torch

# Example tensor of shape (B, N, d)
B, N, d = 2, 1, 2  # Example sizes
x = torch.randn(B, N, d)

n_rep = 5  # Number of times to repeat each row

# Repeat each row n_rep times along dimension 0
x_repeated = x.repeat_interleave(n_rep, dim=0)

print(x)
print(x_repeated)  # Expected shape: (B * n_rep * N, d)


tensor([[[-0.5804, -0.1847]],

        [[ 0.8841, -0.7969]]])
tensor([[[-0.5804, -0.1847]],

        [[-0.5804, -0.1847]],

        [[-0.5804, -0.1847]],

        [[-0.5804, -0.1847]],

        [[-0.5804, -0.1847]],

        [[ 0.8841, -0.7969]],

        [[ 0.8841, -0.7969]],

        [[ 0.8841, -0.7969]],

        [[ 0.8841, -0.7969]],

        [[ 0.8841, -0.7969]]])


In [14]:
a = torch.tensor([1,2,3,4,5,6])
b = torch.tensor([1,9]).unsqueeze(1).expand(-1,3).reshape(2*3,1)
b

tensor([[1],
        [1],
        [1],
        [9],
        [9],
        [9]])